### ISSUE TITLE
Could you provide the commands used

### ISSUE THREAD

**Issue by TimelessNL** [larsks/blog-openldap-dynlist#1]
Hi

I'm trying to reproduce your dynamic memberOf attribute. But could you also provide the commands used? Not all of them are present in your blogpost.

I tried to use ldapadd for most of them but the obmemberof attribute does not show up.

**Comment by larsks** [comment]
I've added a [playbook](https://github.com/larsks/blog-openldap-dynlist/blob/master/playbook.yml) to this repository that completely reproduces the example, using the [osixia/openldap Docker image](https://hub.docker.com/r/osixia/openldap/).
